### ISSUE TITLE
enableAbort() default timeout is too low - default should be configurable.

### ISSUE THREAD

**Issue by Mas2112** [redaxmedia/ngx-crud#16]
When calling enableAbort() without any parameters, the timeout value is very low (maybe 2 seconds). It would be better to have a higher timeout value, something like 60 seconds. 

The default timeout should also be configurable somehow.

**Comment by redaxmedia** [comment]
Since 4.0.0-beta.9 you can disable automated aborting using a zero lifetime:

```
crudService->enableAbort('GET', 0);
```
