### ISSUE TITLE
Code coverage not working with ES2019.

### ISSUE THREAD

**Issue by Mas2112** [redaxmedia/ngx-crud#22]
As you already reported to the Angular team here (https://github.com/angular/angular/issues/34959), code coverage does not work with Injector.

A possible solution would be to just not use Injector. You can instantiate AbortService and CacheService directly.

**Comment by redaxmedia** [comment]
@Mas2112 There is a reason I used the injector - in case someone has to extend the constructor with another dependency - all previous services need to be repeated. See https://github.com/redaxmedia/ngx-crud/commit/c9b5e53594b8c403fddff5893fff8eb0ce64bbd3

Please use `es5` as target to work around this like suggested here: https://github.com/angular/angular-cli/issues/14860 - I am sorry but see no reason to fix a bug that is deep inside Angular itself.
