### ISSUE TITLE
Proposal renaming OptionInterface

### ISSUE THREAD

**Issue by GregOnNet** [redaxmedia/ngx-crud#24]
Hi,

I like to avoid technical expressions when it comes to write abstractions.
That's why I thought it would be cleaner to read if `Interface`-Suffix is removed from `OptionInterface`.

You could either go with Option or CrudOption.

You can close this issue after reading this, since it is just my opinion and the change has no technical impact on the library itself.

**Comment by redaxmedia** [comment]
I will put this under consideration...
